import os
import smtplib
from email.message import EmailMessage

GMAIL_USER = "mimibotx@gmail.com"
RECIPIENT = "taminagurnett@gmail.com"
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587

PROJECT_STATUS = [
    ("Power BI Dashboard Setup", "Script fetching crypto prices done; waiting on Canadian commodity data sources to finalize integration and visuals."),
    ("Canadian Data Fetching", "Drafted scripts, issues finding reliable data sources; exploring gov APIs and export tools."),
    ("Email Update Automation", "Email script created; troubleshooting Gmail SMTP and app password setup."),
    ("Trello Kanban Automation", "Planning task auto-movement based on status; no production code yet."),
    ("Environment Variable Security", "Setup permanent env variables for creds; pending verification."),
    ("Scheduled Task Management", "Tried cron jobs; moving to local script + OS scheduler."),
    ("Data Integration & Processing", "Integration for yfinance and Nasdaq done; waiting on gov data input.")
]

def compose_email(_):
    lines = ["Here’s the current list of active projects with their latest statuses:"]
    for i, (proj, status) in enumerate(PROJECT_STATUS, start=1):
        lines.append(f"{i}. {proj}: {status}")

    lines.append("\n\nThis summary is automatically generated by Mimibot.")

    body = "\n".join(lines)
    msg = EmailMessage()
    msg["Subject"] = "Mimibot Active Projects Status Update"
    msg["From"] = GMAIL_USER
    msg["To"] = RECIPIENT
    msg.set_content(body)
    return msg

def send_email(message):
    with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as smtp:
        smtp.starttls()
        smtp.login(GMAIL_USER, os.getenv("GMAIL_APP_PASSWORD"))
        smtp.send_message(message)

def main():
    email_msg = compose_email(PROJECT_STATUS)
    send_email(email_msg)
    print("Status email sent.")


if __name__ == '__main__':
    main()
